name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      module_evaluation_released: ${{ steps.release.outputs['module/evaluation--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # uses default file names: release-please-config.json + .release-please-manifest.json
          # no extra inputs needed for v4
          # The action will create/refresh a Release PR when there are releasable commits
          # (feat, fix, deps, etc.).
          # See: https://github.com/googleapis/release-please
          token: ${{ secrets.PAT }}
          config-file: .github/release-please/release-please-config.json
          manifest-file: .github/release-please/.release-please-manifest.json

  check-release:
    permissions:
      actions: read
    if: ${{ needs.release-please.outputs.module_evaluation_released == 'true' }}
    uses: ./.github/workflows/bump-modules.yml
    needs: release-please
    with:
      modulePath: module/evaluation
