name: update-internal-module

on:
    push:
        branches: [main]

permissions:
    contents: write
    pull-requests: write

jobs:
    main-release:
        if: ${{ startsWith(github.event.release.tag_name, 'module/evaluation') }}
        name: check if release is a module/evaluation release
        runs-on: ubuntu-latest
        steps:
            - name: Extract and print version
              run: |
                  VERSION=${GITHUB_REF#refs/tags/module/evaluation/}
                  echo "Version: $VERSION"
